services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - ./backend:/app
      - ./shared:/app/shared
      - backend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: ./entrypoint.sh
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - ./shared:/app/shared
      - frontend_node_modules:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://backend:4001
      - HOST=0.0.0.0
    depends_on:
      - backend
    command: ./entrypoint.sh
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules:
